### ISSUE TITLE
stack trace: unable to remove file:sveltekit-zero-api.tgz on node install

### ISSUE THREAD

**Issue by kauderk** [Refzlund/sveltekit-zero-api#11]
sveltekit-zero-api.tgz isn't reconized on a cold start by the package.json, install.js and pack.js
"sveltekit-zero-api": "file:sveltekit-zero-api.tgz",

commenting out `execSync('pnpm remove -D sveltekit-zero-api', { stdio: 'inherit' })` on install.js and pack.js lets me start the dev server, I think it's a temporary issue

```bash
sveltekit-zero-api> pnpm i
Lockfile is up to date, resolution step is skipped
Already up to date
sveltekit-zero-api> node install
Installing node modules...
Lockfile is up to date, resolution step is skipped
Already up to date
Packaging
... An error occurred:
node:internal/errors:863
  const err = new Error(message);
              ^

Error: Command failed: pnpm remove sveltekit-zero-api
    at checkExecSyncError (node:child_process:871:11)
    at execSync (node:child_process:943:15)   
    at file:///C:/open_source_repos/sveltekit-zero-api/pack.js:11:2
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:527:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12) {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(273) [Uint8Array] [
      226, 128, 137,  69,  82,  82,  95,  80, 
 78,  80,  77,  95,
       67,  65,  78,  78,  79,  84,  95,  82, 
 69,  77,  79,  86,
       69,  95,  77,  73,  83,  83,  73,  78, 
 71,  95,  68,  69,
       80,  83, 226, 128, 137,  32,  67,  97, 
110, 110, 111, 116,
       32, 114, 101, 109, 111, 118, 101,  32, 
 39, 115, 118, 101,
      108, 116, 101, 107, 105, 116,  45, 122, 
101, 114, 111,  45,
       97, 112, 105,  39,  58,  32, 110, 111, 
 32, 115, 117,  99,
      104,  32, 100, 101, 112, 101, 110, 100, 
101, 110,  99, 121,
       32, 102, 111, 117,
      ... 173 more items
    ],
    Buffer(0) [Uint8Array] []
  ],
  pid: 8032,
  stdout: Buffer(273) [Uint8Array] [
    226, 128, 137,  69,  82,  82,  95,  80,  78,  80,  77,  95,
     67,  65,  78,  78,  79,  84,  95,  82,  69,  77,  79,  86,
     69,  95,  77,  73,  83,  83,  73,  78,  71,  95,  68,  69,
     80,  83, 226, 128, 137,  32,  67,  97, 110, 110, 111, 116,
     32, 114, 101, 109, 111, 118, 101,  32,  39, 115, 118, 101,
    108, 116, 101, 107, 105, 116,  45, 122, 101, 114, 111,  45,
     97, 112, 105,  39,  58,  32, 110, 111,  32, 115, 117,  99,
    104,  32, 100, 101, 112, 101, 110, 100, 101, 110,  99, 121,
     32, 102, 111, 117,
    ... 173 more items
  ],
  stderr: Buffer(0) [Uint8Array] []
}

Node.js v18.9.0
node:internal/errors:863
  const err = new Error(message);
              ^

Error: Command failed: node pack
    at checkExecSyncError (node:child_process:871:11)
    at execSync (node:child_process:943:15)   
    at file:///C:/open_source_repos/sveltekit-zero-api/install.js:13:1
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:527:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 5180,
  stdout: null,
  stderr: null
}

Node.js v18.9.0
sveltekit-zero-api> node install
Installing node modules...
Lockfile is up to date, resolution step is skipped
Already up to date
Packaging
Extracting pack
Progress: resolved 1, reused 0, downloaded 0, 
Progress: resolved 32, reused 31, downloaded 1 WARN  deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead     
Progress: resolved 32, reused 31, downloaded 1Progress: resolved 102, reused 101, downloadedPackages: +1
+
Progress: resolved 102, reused 101, downloadedProgress: resolved 137, reused 114, downloaded

devDependencies:
+ sveltekit-zero-api 0.12.1

Progress: resolved 137, reused 114, downloadedProgress: resolved 137, reused 114, downloaded 1, added 1, done
Completed

> sveltekit-zero-api@0.12.1 dev C:\open_source_repos\sveltekit-zero-api
> pnpm add -D ./sveltekit-zero-api.tgz && set 
NODE_ENV=zeroapi && vite dev

Progress: resolved 0, reused 1, downloaded 0, 
Progress: resolved 27, reused 27, downloaded 0 WARN  deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead     
Progress: resolved 27, reused 27, downloaded 0Progress: resolved 109, reused 86, downloaded 
Already up to date
Progress: resolved 109, reused 86, downloaded 
Progress: resolved 137, reused 115, downloaded 0, added 0, done

Forced re-optimization of dependencies
[DEBUG] Updating $types at C:\open_source_repos\sveltekit-zero-api\.svelte-kit\types\src\routes\(app)\about\[slug]\$types.d.ts ...
[DEBUG] Updating $types at C:\open_source_repos\sveltekit-zero-api\.svelte-kit\types\src\routes\(app)\api\fo\$types.d.ts ...
[DEBUG] Updating $types at C:\open_source_repos\sveltekit-zero-api\.svelte-kit\types\src\routes\(app)\api\fo\[sluggers]\$types.d.ts ...
[DEBUG] Updating $types at C:\open_source_repos\sveltekit-zero-api\.svelte-kit\types\src\routes\(app)\api\test\$types.d.ts ...
[DEBUG] Updating $types at C:\open_source_repos\sveltekit-zero-api\.svelte-kit\types\src\routes\(app)\api\[id=integer]\$types.d.ts ...
(node:2772) Warning: No such label '[DEBUG] Updated generated types at C:\open_source_repos\sveltekit-zero-api\.svelte-kit\types\src\sveltekit-zero-api.d.ts ...' for console.timeEnd()       
(Use `node --trace-warnings ...` to show where the warning was created)

  VITE v4.1.4  ready in 3209 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
```

**Comment by Refzlund** [comment]
Hey! Sorry for the laaaate reply!

Thanks for providing the standalone support. I'll look into it later today and merge your work. Thank yoooou very much🦒

**Comment by Refzlund** [comment]
Removed `pack.js` and `install.js` as they're not required anymore
